i3lock: Use only i3lock-color, no fallback to i3lock

diff --git a/scripts/i3lock-fancy/lock b/scripts/i3lock-fancy/lock
--- a/scripts/i3lock-fancy/lock
+++ b/scripts/i3lock-fancy/lock
@@ -3,7 +3,7 @@
 # Make sure everything that is needed is available
 command -v convert > /dev/null 2>&1 || { echo >&2 "imagemagick is not installed, aborting"; exit 1; }
 command -v scrot > /dev/null 2>&1 || { echo >&2 "scrot is not installed, aborting"; exit 1; }
-command -v i3lock > /dev/null 2>&1 || { echo >&2 "i3lock is not installed, aborting"; exit 1; }
+command -v i3lock-color > /dev/null 2>&1 || { echo >&2 "i3lock-color is not installed, aborting"; exit 1; }
 
 IMAGE=$(mktemp --suffix .png)
 scrot $IMAGE
@@ -51,16 +51,11 @@ convert $IMAGE \
 # draw once again and what you got is only outer stroke :)
 
 # Try to run i3lock-color
-i3lock \
+i3lock-color \
 	--insidevercolor=00000000 --insidewrongcolor=00000000 --insidecolor=00000000 \
 	--ringvercolor=$FG_COLOR --ringwrongcolor=$WRONG_COLOR --ringcolor=464340ff \
 	--linecolor=00000000 --textcolor=00000000 \
 	--keyhlcolor=$FG_COLOR --bshlcolor=$WRONG_COLOR \
 	-i $IMAGE > /dev/null
-
-# Fallback to i3lock
-if [ $? -eq 1 ]; then
-	i3lock -u -i $IMAGE
-fi
 
 rm $IMAGE
